# Generated by Django 5.1.3 on 2025-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(max_length=10),
        ),
    ]
